package com.restaurant;

import javax.swing.*;
import javax.swing.border.CompoundBorder;
import javax.swing.border.EmptyBorder;
import javax.swing.border.LineBorder;
import javax.swing.border.TitledBorder;
import java.awt.*;
import java.awt.event.ActionEvent;
import java.awt.print.PrinterException;
import java.text.MessageFormat;
import java.util.List;

public class RestaurantBillingSystem extends JFrame {

    private final MenuManager menuManager;
    private final BillingManager billingManager;

    public RestaurantBillingSystem() {
        this.menuManager = new MenuManager();
        this.billingManager = new BillingManager();

        initComponents();
        customInit();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        headerPanel = new com.restaurant.GradientHeaderPanel(new java.awt.Color(255, 75, 75), new java.awt.Color(255, 140, 0));
        lblLogo = new javax.swing.JLabel();
        headerTextPanel = new javax.swing.JPanel();
        lblTitle = new javax.swing.JLabel();
        lblSubTitle = new javax.swing.JLabel();
        mainCenterPanel = new javax.swing.JPanel();
        orderPanel = new com.restaurant.CardPanel(java.awt.Color.WHITE, new java.awt.Color(226, 232, 240));
        lblCat = new javax.swing.JLabel();
        cmbCategory = new javax.swing.JComboBox<>();
        lblItem = new javax.swing.JLabel();
        cmbItems = new javax.swing.JComboBox<>();
        lblQty = new javax.swing.JLabel();
        spnQuantity = new javax.swing.JSpinner();
        btnAddOrder = new com.restaurant.ModernVibrantButton("Add Item to Order", new java.awt.Color(16, 185, 129));
        btnTotalBill = new com.restaurant.ModernVibrantButton("Generate Total Bill", new java.awt.Color(249, 115, 22));
        receiptPanel = new com.restaurant.CardPanel(java.awt.Color.WHITE, new java.awt.Color(226, 232, 240));
        scrollPane = new javax.swing.JScrollPane();
        txtReceipt = new javax.swing.JTextArea();
        receiptButtonPanel = new javax.swing.JPanel();
        btnPrint = new com.restaurant.ModernVibrantButton("Print Receipt", new java.awt.Color(59, 130, 246));
        btnClear = new com.restaurant.ModernVibrantButton("Clear / New Order", new java.awt.Color(244, 63, 94));
        footerPanel = new com.restaurant.GradientHeaderPanel(new java.awt.Color(15, 23, 42), new java.awt.Color(30, 41, 59));
        lblFooterBrand = new javax.swing.JLabel();
        lblGrandTotal = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Foodie's Paradise - Order & Billing System");
        setMinimumSize(new java.awt.Dimension(880, 640));
        setPreferredSize(new java.awt.Dimension(980, 720));

        headerPanel.setLayout(new java.awt.BorderLayout());
        headerPanel.add(lblLogo, java.awt.BorderLayout.WEST);

        headerTextPanel.setOpaque(false);
        headerTextPanel.setLayout(new java.awt.GridLayout(2, 1));

        lblTitle.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lblTitle.setForeground(new java.awt.Color(255, 255, 255));
        lblTitle.setText("FOODIE'S PARADISE");
        headerTextPanel.add(lblTitle);

        lblSubTitle.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblSubTitle.setForeground(new java.awt.Color(255, 241, 230));
        lblSubTitle.setText("Fast, Modern & Smart Restaurant Billing System");
        headerTextPanel.add(lblSubTitle);

        headerPanel.add(headerTextPanel, java.awt.BorderLayout.CENTER);

        getContentPane().add(headerPanel, java.awt.BorderLayout.NORTH);

        mainCenterPanel.setOpaque(false);
        mainCenterPanel.setLayout(new java.awt.GridLayout(1, 2, 15, 0));

        orderPanel.setLayout(new javax.swing.BoxLayout(orderPanel, javax.swing.BoxLayout.Y_AXIS));

        lblCat.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblCat.setText("Select Category:");
        orderPanel.add(lblCat);
        orderPanel.add(cmbCategory);

        lblItem.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblItem.setText("Select Menu Item:");
        orderPanel.add(lblItem);
        orderPanel.add(cmbItems);

        lblQty.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblQty.setText("Quantity:");
        orderPanel.add(lblQty);

        spnQuantity.setModel(new javax.swing.SpinnerNumberModel(1, 1, 999, 1));
        orderPanel.add(spnQuantity);

        btnAddOrder.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddOrderActionPerformed(evt);
            }
        });
        orderPanel.add(btnAddOrder);

        btnTotalBill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTotalBillActionPerformed(evt);
            }
        });
        orderPanel.add(btnTotalBill);

        mainCenterPanel.add(orderPanel);

        receiptPanel.setLayout(new java.awt.BorderLayout(0, 12));

        txtReceipt.setEditable(false);
        txtReceipt.setColumns(20);
        txtReceipt.setRows(5);
        scrollPane.setViewportView(txtReceipt);

        receiptPanel.add(scrollPane, java.awt.BorderLayout.CENTER);

        receiptButtonPanel.setOpaque(false);
        receiptButtonPanel.setLayout(new java.awt.GridLayout(1, 2, 12, 0));

        btnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrintActionPerformed(evt);
            }
        });
        receiptButtonPanel.add(btnPrint);

        btnClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnClearActionPerformed(evt);
            }
        });
        receiptButtonPanel.add(btnClear);

        receiptPanel.add(receiptButtonPanel, java.awt.BorderLayout.SOUTH);

        mainCenterPanel.add(receiptPanel);

        getContentPane().add(mainCenterPanel, java.awt.BorderLayout.CENTER);

        footerPanel.setLayout(new java.awt.BorderLayout());

        lblFooterBrand.setFont(new java.awt.Font("Segoe UI", 1, 13)); // NOI18N
        lblFooterBrand.setForeground(new java.awt.Color(226, 232, 240));
        lblFooterBrand.setText("Foodie's Paradise Billing System");
        footerPanel.add(lblFooterBrand, java.awt.BorderLayout.WEST);

        lblGrandTotal.setFont(new java.awt.Font("Segoe UI", 1, 17)); // NOI18N
        lblGrandTotal.setForeground(new java.awt.Color(250, 204, 21));
        lblGrandTotal.setText("Current Total: ₹0.00");
        footerPanel.add(lblGrandTotal, java.awt.BorderLayout.EAST);

        getContentPane().add(footerPanel, java.awt.BorderLayout.SOUTH);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private JLabel lblOrderCount;
    private JLabel lblTaxNotice;

    private void customInit() {
        setTitle("Foodie's Paradise - Order & Billing System");
        setExtendedState(JFrame.MAXIMIZED_BOTH);
        setSize(1100, 750);
        setMinimumSize(new Dimension(900, 650));
        setLocationRelativeTo(null);

        Color bgLight = new Color(241, 245, 249);
        Color textColor = new Color(15, 23, 42);
        Color labelColor = new Color(51, 65, 85);
        Color borderLight = new Color(226, 232, 240);

        Container contentPane = getContentPane();
        contentPane.setLayout(new BorderLayout(0, 0));
        contentPane.setBackground(bgLight);

        // Outer Content Container with Padding
        JPanel centerWrapper = new JPanel(new BorderLayout(15, 15));
        centerWrapper.setOpaque(false);
        centerWrapper.setBorder(new EmptyBorder(15, 20, 15, 20));

        centerWrapper.add(headerPanel, BorderLayout.NORTH);
        centerWrapper.add(mainCenterPanel, BorderLayout.CENTER);

        contentPane.removeAll();
        contentPane.add(centerWrapper, BorderLayout.CENTER);
        contentPane.add(footerPanel, BorderLayout.SOUTH);

        // Header Panel Padding & Logo Setup
        headerPanel.setBorder(new EmptyBorder(15, 25, 15, 25));
        try {
            java.net.URL imgURL = getClass().getResource("/com/restaurant/logo.png");
            if (imgURL == null) {
                imgURL = getClass().getResource("/com/restaurant/logo.png.png");
            }
            if (imgURL != null) {
                ImageIcon rawIcon = new ImageIcon(imgURL);
                Image scaledImg = rawIcon.getImage().getScaledInstance(70, 70, Image.SCALE_SMOOTH);
                lblLogo.setIcon(new ImageIcon(scaledImg));
            }
        } catch (Exception e) {
            System.out.println("Logo load info: " + e.getMessage());
        }

        // Order Panel Border & Spacing
        orderPanel.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createTitledBorder(
                        BorderFactory.createLineBorder(borderLight, 1, true),
                        " Create Order ",
                        TitledBorder.LEFT,
                        TitledBorder.TOP,
                        new Font("Segoe UI", Font.BOLD, 15),
                        textColor
                ),
                new EmptyBorder(18, 22, 18, 22)
        ));

        lblCat.setForeground(labelColor);
        lblItem.setForeground(labelColor);
        lblQty.setForeground(labelColor);

        styleControlBorder(cmbCategory);
        styleControlBorder(cmbItems);
        styleControlBorder(spnQuantity);

        cmbCategory.setMaximumSize(new Dimension(Integer.MAX_VALUE, 40));
        cmbItems.setMaximumSize(new Dimension(Integer.MAX_VALUE, 40));
        spnQuantity.setMaximumSize(new Dimension(Integer.MAX_VALUE, 40));
        spnQuantity.setAlignmentX(Component.LEFT_ALIGNMENT);

        JSpinner.DefaultEditor editor = (JSpinner.DefaultEditor) spnQuantity.getEditor();
        editor.getTextField().setFont(new Font("Segoe UI", Font.BOLD, 15));
        editor.getTextField().setHorizontalAlignment(JTextField.CENTER);
        editor.getTextField().setForeground(textColor);

        // Order Info Box at the bottom to balance receipt panel height
        JPanel infoBox = new JPanel(new GridLayout(2, 1, 0, 4));
        infoBox.setBackground(new Color(248, 250, 252));
        infoBox.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createLineBorder(new Color(226, 232, 240), 1, true),
                new EmptyBorder(10, 14, 10, 14)
        ));
        infoBox.setMaximumSize(new Dimension(Integer.MAX_VALUE, 65));
        infoBox.setAlignmentX(Component.LEFT_ALIGNMENT);

        lblOrderCount = new JLabel("Items In Order: 0");
        lblOrderCount.setFont(new Font("Segoe UI", Font.BOLD, 13));
        lblOrderCount.setForeground(new Color(71, 85, 105));

        lblTaxNotice = new JLabel("Prices exclude 5% GST (added at billing)");
        lblTaxNotice.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        lblTaxNotice.setForeground(new Color(100, 116, 139));

        infoBox.add(lblOrderCount);
        infoBox.add(lblTaxNotice);

        // Re-arrange order panel children cleanly
        orderPanel.removeAll();
        orderPanel.add(lblCat);
        orderPanel.add(Box.createRigidArea(new Dimension(0, 6)));
        orderPanel.add(cmbCategory);
        orderPanel.add(Box.createRigidArea(new Dimension(0, 14)));
        orderPanel.add(lblItem);
        orderPanel.add(Box.createRigidArea(new Dimension(0, 6)));
        orderPanel.add(cmbItems);
        orderPanel.add(Box.createRigidArea(new Dimension(0, 14)));
        orderPanel.add(lblQty);
        orderPanel.add(Box.createRigidArea(new Dimension(0, 6)));
        orderPanel.add(spnQuantity);
        orderPanel.add(Box.createRigidArea(new Dimension(0, 24)));
        orderPanel.add(btnAddOrder);
        orderPanel.add(Box.createRigidArea(new Dimension(0, 12)));
        orderPanel.add(btnTotalBill);
        orderPanel.add(Box.createVerticalGlue());
        orderPanel.add(infoBox);

        // Receipt Panel Border & Warm Text Area Styling
        receiptPanel.setBorder(BorderFactory.createCompoundBorder(
                BorderFactory.createTitledBorder(
                        BorderFactory.createLineBorder(borderLight, 1, true),
                        " Live Receipt & Order Summary ",
                        TitledBorder.LEFT,
                        TitledBorder.TOP,
                        new Font("Segoe UI", Font.BOLD, 15),
                        textColor
                ),
                new EmptyBorder(18, 18, 18, 18)
        ));

        txtReceipt.setFont(new Font("Consolas", Font.PLAIN, 13));
        txtReceipt.setBackground(new Color(254, 252, 232));
        txtReceipt.setForeground(new Color(30, 27, 75));
        txtReceipt.setMargin(new Insets(12, 12, 12, 12));
        scrollPane.setBorder(BorderFactory.createLineBorder(new Color(254, 215, 170), 1));

        receiptButtonPanel.setBorder(new EmptyBorder(10, 0, 0, 0));

        // 100% Full-Width Footer Bar
        footerPanel.setBorder(new EmptyBorder(12, 24, 12, 24));
        lblFooterBrand.setFont(new Font("Segoe UI", Font.BOLD, 14));
        lblFooterBrand.setForeground(new Color(226, 232, 240));

        lblGrandTotal.setFont(new Font("Segoe UI", Font.BOLD, 18));
        lblGrandTotal.setForeground(new Color(250, 204, 21));

        // Populate Categories and Items
        cmbCategory.removeAllItems();
        for (String cat : menuManager.getCategories()) {
            cmbCategory.addItem(cat);
        }
        cmbCategory.addActionListener(e -> updateItemList());
        updateItemList();
    }

    private void styleControlBorder(JComponent comp) {
        comp.setBorder(new CompoundBorder(
                new LineBorder(new Color(203, 213, 225), 1, true),
                new EmptyBorder(4, 8, 4, 8)
        ));
    }

    private void updateItemList() {
        cmbItems.removeAllItems();
        String selectedCategory = (String) cmbCategory.getSelectedItem();
        List<MenuManager.MenuItem> items = menuManager.getItemsByCategory(selectedCategory);
        if (items != null) {
            for (MenuManager.MenuItem item : items) {
                cmbItems.addItem(item.getName() + " - ₹" + (int) item.getPrice());
            }
        }
    }

    private void btnAddOrderActionPerformed(ActionEvent evt) {
        try {
            int qty = (Integer) spnQuantity.getValue();
            if (qty <= 0) {
                JOptionPane.showMessageDialog(this, "Quantity must be greater than 0.", "Invalid Input", JOptionPane.WARNING_MESSAGE);
                return;
            }

            int selectedIndex = cmbItems.getSelectedIndex();
            if (selectedIndex < 0) return;

            String selectedItemStr = (String) cmbItems.getSelectedItem();
            String itemName = selectedItemStr.split(" - ₹")[0];
            double price = menuManager.getPrice(itemName);

            billingManager.addItem(itemName, qty, price);

            double subtotal = billingManager.calculateGrandTotal();
            double grandTotal = subtotal * 1.05;

            txtReceipt.setText(ReceiptGenerator.generateLiveSummary(billingManager.getCurrentOrder()));
            lblGrandTotal.setText(String.format("Current Total (incl. GST): ₹%.2f", grandTotal));
            if (lblOrderCount != null) {
                lblOrderCount.setText("Items In Order: " + billingManager.getCurrentOrder().size());
            }
            spnQuantity.setValue(1);

        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Please enter a valid quantity.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnTotalBillActionPerformed(ActionEvent evt) {
        if (billingManager.isEmpty()) {
            JOptionPane.showMessageDialog(this, "No items ordered yet!", "Empty Order", JOptionPane.INFORMATION_MESSAGE);
            return;
        }

        double subtotal = billingManager.calculateGrandTotal();
        double grandTotal = subtotal * 1.05;
        String finalReceipt = ReceiptGenerator.generateReceipt(billingManager.getCurrentOrder(), subtotal);
        txtReceipt.setText(finalReceipt);
        lblGrandTotal.setText(String.format("Final Total (incl. GST): ₹%.2f", grandTotal));
    }

    private void btnPrintActionPerformed(ActionEvent evt) {
        if (txtReceipt.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(this, "There is no receipt to print!", "Empty Receipt", JOptionPane.WARNING_MESSAGE);
            return;
        }

        try {
            boolean complete = txtReceipt.print(
                    new MessageFormat("Foodie's Paradise - Receipt"),
                    new MessageFormat("Page {0}"),
                    true,
                    null,
                    null,
                    true
            );

            if (complete) {
                JOptionPane.showMessageDialog(this, "Receipt printed successfully!", "Success", JOptionPane.INFORMATION_MESSAGE);
            }
        } catch (PrinterException e) {
            JOptionPane.showMessageDialog(this, "Printing failed: " + e.getMessage(), "Print Error", JOptionPane.ERROR_MESSAGE);
        }
    }

    private void btnClearActionPerformed(ActionEvent evt) {
        billingManager.reset();
        txtReceipt.setText("");
        lblGrandTotal.setText("Current Total: ₹0.00");
        if (lblOrderCount != null) {
            lblOrderCount.setText("Items In Order: 0");
        }
        if (cmbCategory.getItemCount() > 0) {
            cmbCategory.setSelectedIndex(0);
        }
        spnQuantity.setValue(1);
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAddOrder;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnPrint;
    private javax.swing.JButton btnTotalBill;
    private javax.swing.JComboBox<String> cmbCategory;
    private javax.swing.JComboBox<String> cmbItems;
    private javax.swing.JPanel footerPanel;
    private javax.swing.JPanel headerPanel;
    private javax.swing.JPanel headerTextPanel;
    private javax.swing.JLabel lblCat;
    private javax.swing.JLabel lblFooterBrand;
    private javax.swing.JLabel lblGrandTotal;
    private javax.swing.JLabel lblItem;
    private javax.swing.JLabel lblLogo;
    private javax.swing.JLabel lblQty;
    private javax.swing.JLabel lblSubTitle;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JPanel mainCenterPanel;
    private javax.swing.JPanel orderPanel;
    private javax.swing.JPanel receiptButtonPanel;
    private javax.swing.JPanel receiptPanel;
    private javax.swing.JScrollPane scrollPane;
    private javax.swing.JSpinner spnQuantity;
    private javax.swing.JTextArea txtReceipt;
    // End of variables declaration//GEN-END:variables
}
