package javaapplication;



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
    /**
     * 
 *
 * @author Manvi Walam
 */
public class NewJFrame extends javax.swing.JFrame {
    double grandTotal = 0.0;
    StringBuilder orderSummary = new StringBuilder();
   
    
        public NewJFrame() {
        initComponents();
        
                this.setLocationRelativeTo(null);
                this.getContentPane().setBackground(new java.awt.Color(34,47,62));

        
        // Scale logo image down to fit inside the label cleanly
    try {
    java.net.URL imgURL = getClass().getResource("/javaapplication/logo.png"); 
    if (imgURL == null) {
        // Fallback check if double extension is present on disk
        imgURL = getClass().getResource("/javaapplication/logo.png.png"); 
    }
    
    if (imgURL != null) {
    javax.swing.ImageIcon rawIcon = new javax.swing.ImageIcon(imgURL);
    java.awt.Image scaledImg = rawIcon.getImage().getScaledInstance(300, 300, java.awt.Image.SCALE_SMOOTH);
    jLabel1.setIcon(new javax.swing.ImageIcon(scaledImg));
    jLabel1.setText(""); 

    // 1. Give jLabel1 explicit dimensions and place it at the TOP CENTER
    jLabel1.setBounds(630, 5, 300, 300); 

    // 2. FORCE jLabel1 to sit on top of jLabel2 (the background)
    this.getContentPane().setComponentZOrder(jLabel1, 0); 
}
    } catch (Exception e) {
    System.out.println("Error scaling logo: " + e.getMessage());
}
        
        }
        

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        cmbItems = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        txtQuantity = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtReceipt = new javax.swing.JTextArea();
        btnPrint = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Restaurant Billing System");
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(253, 246, 227));
        getContentPane().setLayout(null);

        jLabel3.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel3.setText("Select Item:");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(460, 350, 100, 20);

        cmbItems.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Paneer Butter Masala - ₹180", "Veg Biryani - ₹150", "Chicken Biryani - ₹220", "Masala Dosa - ₹100", "Idli Sambar - ₹80", "Chole Bhature - ₹120", "Pav Bhaji - ₹110", "Fried Rice - ₹130", "Noodles - ₹140", "Manchurian - ₹160", "Dal Tadka - ₹100", "Roti - ₹20", "Naan - ₹40", "Butter Chicken - ₹250", "Fish Curry - ₹300", "Mutton Curry - ₹350", "Cold Coffee - ₹90", "Ice Cream - ₹70", "Soft Drink - ₹50", "Gulab Jamun - ₹60", " " }));
        cmbItems.addActionListener(this::cmbItemsActionPerformed);
        getContentPane().add(cmbItems);
        cmbItems.setBounds(550, 350, 212, 22);

        jLabel4.setFont(new java.awt.Font("Segoe UI Semibold", 0, 14)); // NOI18N
        jLabel4.setText("Quantity:");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(460, 410, 78, 27);
        getContentPane().add(txtQuantity);
        txtQuantity.setBounds(550, 410, 71, 22);

        jButton1.setBackground(new java.awt.Color(0, 153, 51));
        jButton1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Order");
        jButton1.setFocusPainted(false);
        jButton1.addActionListener(this::jButton1ActionPerformed);
        getContentPane().add(jButton1);
        jButton1.setBounds(940, 350, 132, 27);

        jButton2.setBackground(new java.awt.Color(211, 84, 0));
        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(255, 255, 255));
        jButton2.setText("Total Bill");
        jButton2.setFocusPainted(false);
        jButton2.addActionListener(this::jButton2ActionPerformed);
        getContentPane().add(jButton2);
        jButton2.setBounds(940, 410, 132, 27);

        jLabel1.setText("jLabel1");
        jLabel1.setMaximumSize(new java.awt.Dimension(200, 200));
        jLabel1.setMinimumSize(new java.awt.Dimension(200, 200));
        jLabel1.setPreferredSize(new java.awt.Dimension(200, 200));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(690, 40, 200, 200);

        txtReceipt.setBackground(new java.awt.Color(34, 47, 62));
        txtReceipt.setColumns(20);
        txtReceipt.setFont(new java.awt.Font("Consolas", 0, 12)); // NOI18N
        txtReceipt.setForeground(new java.awt.Color(255, 255, 255));
        txtReceipt.setRows(5);
        txtReceipt.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(10, 10, 10, 10), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(189, 195, 199))));
        txtReceipt.setCaretColor(new java.awt.Color(255, 255, 255));
        jScrollPane1.setViewportView(txtReceipt);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(460, 460, 616, 239);

        btnPrint.setBackground(new java.awt.Color(41, 128, 185));
        btnPrint.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnPrint.setForeground(new java.awt.Color(255, 255, 255));
        btnPrint.setText("Print Receipt");
        btnPrint.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(6, 15, 6, 15), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(31, 97, 141))));
        btnPrint.setBorderPainted(false);
        btnPrint.setFocusPainted(false);
        btnPrint.setFocusable(false);
        btnPrint.addActionListener(this::btnPrintActionPerformed);
        getContentPane().add(btnPrint);
        btnPrint.setBounds(580, 730, 130, 34);

        btnClear.setBackground(new java.awt.Color(255, 0, 51));
        btnClear.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        btnClear.setForeground(new java.awt.Color(255, 255, 255));
        btnClear.setText("Clear");
        btnClear.setBorder(javax.swing.BorderFactory.createCompoundBorder(javax.swing.BorderFactory.createEmptyBorder(6, 15, 6, 15), javax.swing.BorderFactory.createLineBorder(new java.awt.Color(146, 43, 33))));
        btnClear.setBorderPainted(false);
        btnClear.setFocusPainted(false);
        btnClear.setFocusable(false);
        btnClear.addActionListener(this::btnClearActionPerformed);
        getContentPane().add(btnClear);
        btnClear.setBounds(890, 730, 67, 34);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/javaapplication/bg1.jpeg"))); // NOI18N
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1536, 1024);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
   
    try {
        String qtyText = txtQuantity.getText().trim();
        if (qtyText.isEmpty()) {
            javax.swing.JOptionPane.showMessageDialog(null, "Please enter valid quantity.");
            return;
        }

        int qty = Integer.parseInt(qtyText);
        if (qty <= 0) {
            javax.swing.JOptionPane.showMessageDialog(null, "Quantity must be greater than 0.");
            return;
        }

        String selectedItemStr = (String) cmbItems.getSelectedItem();
        String[] parts = selectedItemStr.split(" - ₹");
        String itemName = parts[0];
        double price = Double.parseDouble(parts[1]);

        double amount = qty * price;
        grandTotal += amount;

        orderSummary.append(qty)
                    .append(" x ")
                    .append(itemName)
                    .append(" - ₹")
                    .append((int) price)
                    .append(" = ₹")
                    .append(amount)
                    .append("\n");

        txtReceipt.setText(orderSummary.toString());
        txtQuantity.setText("");

    } catch (NumberFormatException ex) {
        javax.swing.JOptionPane.showMessageDialog(null, "Please enter valid quantity.");
    }



        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void cmbItemsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbItemsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbItemsActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    if (grandTotal == 0) {
        javax.swing.JOptionPane.showMessageDialog(null, "No items ordered yet!");
        return;
    }

    // Format current date & time (dd/MM/yyyy HH:mm:ss)
    java.text.SimpleDateFormat formatter = new java.text.SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
    String currentDateTime = formatter.format(new java.util.Date());

    // Build the final receipt display
    StringBuilder bill = new StringBuilder(orderSummary.toString());
    bill.append("-----------------------------\n");
    bill.append("Total Amount: ₹").append(grandTotal).append("\n");
    bill.append("Date & Time: ").append(currentDateTime).append("\n");
    bill.append("-----------------------------\n");
    bill.append("   Thank You! Visit Again!   ");

    // Output to the Receipt text area
    txtReceipt.setText(bill.toString());
   
       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void btnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrintActionPerformed
    // Check if there's anything to print first
    if (txtReceipt.getText().trim().isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this, "There is no receipt to print!");
        return;
    }

    try {
        // Send the text area directly to the system printer
        boolean complete = txtReceipt.print(
            new java.text.MessageFormat("Foodie's Paradise - Receipt"), // Header text
            new java.text.MessageFormat("Page {0}"),                   // Footer text
            true,                                                     // Show interactive print dialog
            null,                                                     // Printer attributes
            null,                                                     // Print request attributes
            true                                                      // Interactive mode
        );

        if (complete) {
            javax.swing.JOptionPane.showMessageDialog(this, "Receipt printed successfully!");
        }
    } catch (java.awt.print.PrinterException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Printing failed: " + e.getMessage());
    }
        // TODO add your handling code here:
    }//GEN-LAST:event_btnPrintActionPerformed

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnClearActionPerformed
    // 1. Reset class tracking variables
    // 1. Clear the receipt text area
    txtReceipt.setText("");
    if(cmbItems.getItemCount() > 0) {
        cmbItems.setSelectedIndex(0);
    
        // TODO add your handling code here:
    }
    }//GEN-LAST:event_btnClearActionPerformed

   
    
    public static void main(String args[]) {
    
   java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
}
  

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnPrint;
    private javax.swing.JComboBox<String> cmbItems;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtQuantity;
    private javax.swing.JTextArea txtReceipt;
    // End of variables declaration//GEN-END:variables

}

